import Head from "next/head";
import React, { useState } from "react";
import {
  Container,
  Box,
  Button,
  Flex,
  Heading,
  HStack,
  Img,
  Stack,
  Text,
  Input,
  Textarea,
  Center,
} from "@chakra-ui/react";
import { useColorModeValue } from "@chakra-ui/react";


export default function openAI() {
  const [guestName, setGuestName] = useState('');
  const [lengthOfStay, setLengthOfStay] = useState('');
  const [experience, setExperience] = useState('');


  const [isLoading, setIsLoading] = useState(false);
  const [response, setResponse] = useState("");

  const getResponseFromOpenAI = async () => {
    setResponse("");
    setIsLoading(true);
    const prompt = `You will generate a review about someone who has recently stayed at your short term rental/airbnb. You will take inputs guest name, length of stay, and Experience: whether or not they were a good guest. Guest name: ${guestName}, length of stay: ${lengthOfStay}, Experience: ${experience}`;
    const response = await fetch("/api/openai", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ prompt: prompt }),
    });

    const data = await response.json();
    setIsLoading(false);
    console.log(data.text);
    setResponse(data.text);
  };

  return (
    <>
      <Head>
        <title>Airbnb Review Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth 
    alignItems='center'
    bgImage={'/images/blob.gif'} 
    bgAttachment='scroll'
    bgSize={'cover'}
    bgPosition={'center'}
    backgroundRepeat="no-repeat">
        <Container >
        <Box
          maxW={{
            base: "xl",
            md: "6xl",
          }}
          mx="auto"
          
          px={{
            base: "6",
            md: "8",
          }}
        >
         
          <Box >
            <Heading 
              // bgGradient='linear(to-l, #7928CA, #FF0080)'
              //  bgClip='text'
              fontSize="6xl"
              fontWeight="extrabold"
              size="4xl"
            >
              Airbnb Review Generator 🏡
            </Heading>
          
            <Text
              fontSize={{
                md: "2xl",
              }}
              bg={useColorModeValue("white", "white")}
              bgClip="text"
              mt="4"
              maxW="lg"
            >
              AI is changing the world, and we're here to help you stay ahead of
              the curve. Join us to get your daily dose of AI. We'll provide you
              with a juicy 3-minute newsletter on everything AI. (Promise you
              it's not boring!)
            </Text>
    
          <label>
          Guest Name:
          <Input variant='outline'   value={guestName} onChange={(e) => setGuestName(e.target.value)} />
        </label>
        <br />
        <label>
          Length of Stay:
          <Input variant='outline'   value={lengthOfStay} onChange={(e) => setLengthOfStay(e.target.value)} />
        </label>
        <br />
        <label>
          Experience:
          <Textarea placeholder='Input any complaints you have about the guest.' value={experience} onChange={(e) => setExperience(e.target.value)} />
        </label>
        <br />
          <Button onClick={getResponseFromOpenAI}>
            Get Response
          </Button>
        

          <div >
            {isLoading ? (
              <div>Waiting for response ...</div>
            ) : (
              <div>{response}</div>
            )}
          </div>
          </Box>
          </Box>
        </Container>
       
      </Container>
    </>
  );
}