import Head from "next/head";
import React, { useState } from "react";


export default function openAI() {
  const [guestName, setGuestName] = useState('');
  const [lengthOfStay, setLengthOfStay] = useState('');
  const [experience, setExperience] = useState('');


  const [isLoading, setIsLoading] = useState(false);
  const [response, setResponse] = useState("");

  const getResponseFromOpenAI = async () => {
    setResponse("");
    setIsLoading(true);
    const prompt = `Write a review for ${guestName} who stayed with us for ${lengthOfStay}. ${experience}`;
    const response = await fetch("/api/openai", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ prompt: prompt }),
    });

    const data = await response.json();
    setIsLoading(false);
    console.log(data.text);
    setResponse(data.text);
  };

  return (
    <>
      <Head>
        <title>Next.js & OpenAI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div >
          <h1 >Next.js & OpenAI Sample Application</h1>
          <label>
          Guest Name:
          <input type="text" value={guestName} onChange={(e) => setGuestName(e.target.value)} />
        </label>
        <br />
        <label>
          Length of Stay:
          <input type="text" value={lengthOfStay} onChange={(e) => setLengthOfStay(e.target.value)} />
        </label>
        <br />
        <label>
          Experience:
          <textarea value={experience} onChange={(e) => setExperience(e.target.value)} />
        </label>
        <br />
          <button onClick={getResponseFromOpenAI}>
            Get Response
          </button>
        

          <div >
            {isLoading ? (
              <div>Waiting for response ...</div>
            ) : (
              <div>{response}</div>
            )}
          </div>
         
        </div>
      </main>
    </>
  );
}